@startuml

' Define classes
class Item {}

class Product {}

class Service {}

class ItemCategory {}

class Warehouse {}

class StockTransaction {}


' Define relationships
Item <|-- Product : extends <
Item <|-- Service : extends <

Item "1" --> "1" ItemCategory : belongs to >
Service "1" --> "0..*" Product : requires >

Warehouse "1..*" --> "0..*" Product : has >

' StockTransaction can reference any Inventory Item
StockTransaction "1" --> "1" Warehouse : occurs in >
StockTransaction "1" --> "1" Item : tracks >



@enduml