@startuml

'USERS

class Ana:User {
    id = 1
    name = Ana
    email = ana@doceana.pt
    password = 123@Ana
    roles = [1]
}

class Nelson:User{
    id = 2
    name = Nelson
    email = nelson@doceana.pt
    password = 123@Nelson
    roles = [2, 3, 4]
}


'END USERS

'ROLES



class MasterAdmin:Role{
    id = 1
    name = master admin
    permissions = [1]
}

class "SalesManager:Role"{
    id = 2
    name = sales manager
    permission = [3, 4]
}


class HRManager:Role{
    id = 3
    name = sales manager
    permission = [3, 4]
}

'END ROLES


'PERMISSIONS

class All:Permission{
    id = 1
    name = all dangerous
    scope = ALL
    level = [ALL]
}

class SalesAll:Permission{
    id = 2
    name = sales all
    scope = SALES
    level = [ALL]
}


class HRAll:Permission{
    id = 4
    name = HR all
    scope = HR
    level = [ALL]
}

'END PERMISSIONS


'RELATIONS

"Ana:User" -DOWN- "MasterAdmin:Role"
"MasterAdmin:Role" -DOWN- "All:Permission"

"Nelson:User" -DOWN- "HRManager:Role"
"HRManager:Role" -DOWN- "HRAll:Permission"

"Nelson:User" -DOWN- "SalesManager:Role"
"SalesManager:Role" -DOWN- "SalesAll:Permission"



'END RELATIONS

@enduml