@startuml
'https://plantuml.com/class-diagram

class User{
    - Integer id
    - String name
    - String email
    - String password
    - List<Role> | void role
    - setId()
    + getId()
    + Name {set;get} ()
    + email {set;get} ()
    + password {set;get} ()
    + role  {set;get} ()
}

class Profile{

}
class Address

class Role
class Permission
class Notification




Collection <|-- AbstractCollection


enum Status {
DAYS
HOURS
MINUTES
}

@enduml