@startuml
'https://plantuml.com/class-diagram

class User{
    - id : Integer
    - name : String
    - email : String
    - password : String
    - roles : List<Role> | void

    - setId()
    + getId()
    + name {set;get} ()
    + email {set;get} ()
    + password {set;get} ()
    + roles  {set;get} ()
}

class Role {
    - id : Integer
    - name : String
    - permissions : List<Permission>

    - setId()
    + getId()
    + name {set;get} ()
    + permissions {set;get} ()
}

class Permission{
    - id : Integer
    - name : String
    - scope : PermissionScope
    - level : List<PermissionLevel>

    - setId()
    + getId()
    + name {set;get} ()
    + scope {set;get} ()
    + level {set;get} ()
}

'class Profile{
'
'}
'
'class Address
'
'
'class Notification


User "1"  o-- "*" Role : > has
Role "*" *-- "1.*" Permission : < has


enum PermissionScope{
    SYSTEM
    USERS
    SALES
    CRM
    INVENTORY
    FINANCE
}

enum PermissionLevel{
    CREATE
    READ
    UPDATE
    DELETE
}

@enduml